### ISSUE TITLE
clicking dropdown buttons goes back to home page

### ISSUE THREAD

**Issue by cuongutd** [Nanakii/summernote-plugins#3]
Not sure if because of bootstrap/jquery version. Mine is bootstrap 4.0 and jquery 2.2.4

I had to add preventDefault() to code to make it work:

click: function (event) {
              event.preventDefault();
              var $button = $(event.target);

**Comment by garhbod** [comment]
Yea needs an `event.preventDefault();` added

**Comment by celestialaly** [comment]
Hey !

I won't have access to a computer for a few days so could you do a Merge Request with the fix ? 

Thanks :)

**Comment by celestialaly** [comment]
should be fixed in cda5d7ca03bfac7817fe298689f09245d7d2f61e
