### ISSUE TITLE
Demo Issue - Cant append normal text under the template 

### ISSUE THREAD

**Issue by sascha1337** [Nanakii/summernote-plugins#5]
When pressing enter, summernote suggests me a new templated label instead of empty new line.
I cant get out of the "template" focus, so writing normal text on bottom is impossble.

any clue?

**Comment by celestialaly** [comment]
What version of bootstrap / jquery are you using ?
Do you have the same problem on the [demo page](http://code.nanakii.fr/summernote-plugins/examples/template.html) ?

Edit : Ok my bad, I didn't see the title... maybe it's a browser issue ?

**Comment by sascha1337** [comment]
Yes i am using your demo. Just insert a template and try to append default
text after the yellow alert type of thing. It wont work

Am 03.10.2016 16:24 schrieb "Raphaël" notifications@github.com:

**Comment by celestialaly** [comment]
I don't know what is the yellow thing you're mentioning. I also can't reproduce your issue, I tested on Chrome, Chromium and Firefox.

Can you provide a screenshot of what it looks like ?
Also, what browser are you using ?

**Comment by forwardomg** [comment]
Something like this
![opop](https://cloud.githubusercontent.com/assets/5165362/19557585/24ea9fee-96cf-11e6-92c5-6bd00b9ae3ab.gif)
if I want to start a new line, first I need switch to the code and then create paragraph.
@sascha1337 Am I right?

**Comment by sascha1337** [comment]
@forwardomg yes this is exactly what im talking about. its not intuitive for the user, who doesnt know HTML
thank you for this gif

**Comment by forwardomg** [comment]
@sascha1337 @Nanakii  +1, We need a solution for people who are not familiar with HTML

**Comment by celestialaly** [comment]
Ok indeed, I didn't see that one.

When you insert the template and press enter, it creates a new line without the label. There is indeed a bug as soon as you type text in the label and then press enter.

I'm going to do a quick fix to add a new paragraph after the inserted template.

**Comment by celestialaly** [comment]
Ok you can test now on the [demo page](http://code.nanakii.fr/summernote-plugins/examples/template.html) it should automatically insert a new paragraph at the end.

Thanks for reporting this issue :)

**Comment by sascha1337** [comment]
This is awesome! Thank you for your commit keep up **great** work !!

**Comment by forwardomg** [comment]
@Nanakii same behavior, after press enter (new line) we get another template element, but not a new paragraph as it should be (my opinion).

**Comment by celestialaly** [comment]
@forwardomg not sure I understand what you're saying. When you add a template it does add a new empty paragraph after without the template element.

If you mean that when you press enter if your cursor is in the label, it creates a new label, I'm not sure how to deal with it.

**Comment by forwardomg** [comment]
@Nanakii my english not so great, I'm sorry for that, but im trying :) . Yes, you right. If we remove empty paragraph after  template elemen we cant create another one when press enter and user who doesnt know HTML can be confused because he does not understand how to create a normal paragraph instead of the element itself.
But ok)
